### ISSUE TITLE
Maybe I find an issue

### ISSUE THREAD

**Issue by Thomson97** [ZehuaJia/Tube-based-MPC-for-nonlinear-systems#1]
Thanks to the author for giving me the opportunity to learn tube-based MPC, which I am very interested in. But when I run your program "Tube_Based_NMPC" I may find a problem. At line 71, the output values are all NaN, and I get a warning: Matrix is singular, close to singular or badly scaled. Results may be inaccurate. RCOND = NaN.
I think this is unreasonable. Then I look at another function "NMPC_get_max_terminal_Tube", here set: alpha0 = sdpvar(1), and W1 = double(W1) / double(alpha0); W2 = double(W2) / double(alpha0);
I found out that "double(alpha0)=NaN", which shouldn't be true. I would love to know the solution, but my level is limited at the moment. Hope you can clear my mind.

![Uploading issue.png…]()

**Comment by ZehuaJia** [comment]
Maybe you don't have the SDPT3 solver installed?
